name: Face to Face with Jesus
favicon: null
layout_spectrum: 0.8602863748092204
typography_spectrum: 0.02096131327562034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#813b46'
    - '#f4e4c0'
    - '#8c7a62'
    - '#b5b6b8'
    - '#271315'
  brandStrength: 0.9709055160637945
  lightness: 0.35961232893168926
  saturation: 0.9251064406707883
  rhythmicContrast: 0.5546418812591583
purpose: []
